SET NOCOUNT ON;

INSERT INTO Districts (Name) VALUES (N'Bogura');
INSERT INTO Districts (Name) VALUES (N'Chapai Nawabganj');
INSERT INTO Districts (Name) VALUES (N'Joypurhat');
INSERT INTO Districts (Name) VALUES (N'Naogaon');
INSERT INTO Districts (Name) VALUES (N'Natore');
INSERT INTO Districts (Name) VALUES (N'Pabna');
INSERT INTO Districts (Name) VALUES (N'Rajshahi');
INSERT INTO Districts (Name) VALUES (N'Sirajganj');
INSERT INTO Districts (Name) VALUES (N'Dinajpur');
INSERT INTO Districts (Name) VALUES (N'Gaibandha');
INSERT INTO Districts (Name) VALUES (N'Kurigram');
INSERT INTO Districts (Name) VALUES (N'Lalmonirhat');
INSERT INTO Districts (Name) VALUES (N'Nilphamari');
INSERT INTO Districts (Name) VALUES (N'Panchagarh');
INSERT INTO Districts (Name) VALUES (N'Rangpur');
INSERT INTO Districts (Name) VALUES (N'Thakurgaon');
INSERT INTO Districts (Name) VALUES (N'Jamalpur');
INSERT INTO Districts (Name) VALUES (N'Mymensingh');
INSERT INTO Districts (Name) VALUES (N'Netrokona');
INSERT INTO Districts (Name) VALUES (N'Sherpur');
INSERT INTO Districts (Name) VALUES (N'Barguna');
INSERT INTO Districts (Name) VALUES (N'Barisal');
INSERT INTO Districts (Name) VALUES (N'Bhola');
INSERT INTO Districts (Name) VALUES (N'Jhalokati');
INSERT INTO Districts (Name) VALUES (N'Patuakhali');
INSERT INTO Districts (Name) VALUES (N'Pirojpur');
INSERT INTO Districts (Name) VALUES (N'Bandarban');
INSERT INTO Districts (Name) VALUES (N'Brahmanbaria');
INSERT INTO Districts (Name) VALUES (N'Chandpur');
INSERT INTO Districts (Name) VALUES (N'Chittagong');
INSERT INTO Districts (Name) VALUES (N'Cumilla');
INSERT INTO Districts (Name) VALUES (N'Cox''s Bazar');
INSERT INTO Districts (Name) VALUES (N'Feni');
INSERT INTO Districts (Name) VALUES (N'Khagrachhari');
INSERT INTO Districts (Name) VALUES (N'Lakshmipur');
INSERT INTO Districts (Name) VALUES (N'Noakhali');
INSERT INTO Districts (Name) VALUES (N'Rangamati');
INSERT INTO Districts (Name) VALUES (N'Dhaka');
INSERT INTO Districts (Name) VALUES (N'Faridpur');
INSERT INTO Districts (Name) VALUES (N'Gazipur');
INSERT INTO Districts (Name) VALUES (N'Gopalganj');
INSERT INTO Districts (Name) VALUES (N'Kishoreganj');
INSERT INTO Districts (Name) VALUES (N'Madaripur');
INSERT INTO Districts (Name) VALUES (N'Manikganj');
INSERT INTO Districts (Name) VALUES (N'Munshiganj');
INSERT INTO Districts (Name) VALUES (N'Narayanganj');
INSERT INTO Districts (Name) VALUES (N'Narsingdi');
INSERT INTO Districts (Name) VALUES (N'Rajbari');
INSERT INTO Districts (Name) VALUES (N'Shariatpur');
INSERT INTO Districts (Name) VALUES (N'Tangail');
INSERT INTO Districts (Name) VALUES (N'Bagerhat');
INSERT INTO Districts (Name) VALUES (N'Chuadanga');
INSERT INTO Districts (Name) VALUES (N'Jashore');
INSERT INTO Districts (Name) VALUES (N'Jhenaida');
INSERT INTO Districts (Name) VALUES (N'Khulna');
INSERT INTO Districts (Name) VALUES (N'Kushtia');
INSERT INTO Districts (Name) VALUES (N'Magura');
INSERT INTO Districts (Name) VALUES (N'Meherpur');
INSERT INTO Districts (Name) VALUES (N'Narail');
INSERT INTO Districts (Name) VALUES (N'Satkhira');
INSERT INTO Districts (Name) VALUES (N'Habiganj');
INSERT INTO Districts (Name) VALUES (N'Moulvibazar');
INSERT INTO Districts (Name) VALUES (N'Sunamganj');
INSERT INTO Districts (Name) VALUES (N'Sylhet');


INSERT INTO Thanas (Name, DistrictId) VALUES (N'Adamdighi', 1);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Bogura Sadar', 1);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Dhunat', 1);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Dhupchanchia', 1);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Gabtali', 1);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Kahaloo', 1);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Nandigram', 1);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Sariakandi', 1);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Shajahanpur', 1);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Sherpur', 1);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Shibganj', 1);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Sonatola', 1);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Mokamtola', 1);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Bholahat', 2);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Gomastapur', 2);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Nachole', 2);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Nawabganj Sadar', 2);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Shibganj', 2);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Akkelpur', 3);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Joypurhat Sadar', 3);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Kalai', 3);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Khetlal', 3);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Panchbibi', 3);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Atrai', 4);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Badalgachhi', 4);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Dhamoirhat', 4);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Manda', 4);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Mohadevpur', 4);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Naogaon Sadar', 4);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Niamatpur', 4);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Patnitala', 4);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Porsha', 4);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Raninagar', 4);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Sapahar', 4);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Bagatipara', 5);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Baraigram', 5);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Gurudaspur', 5);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Lalpur', 5);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Naldanga', 5);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Natore Sadar', 5);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Singra', 5);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Atgharia', 6);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Bera', 6);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Bhangura', 6);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Chatmohar', 6);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Faridpur', 6);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Ishwardi', 6);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Pabna Sadar', 6);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Santhia', 6);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Sujanagar', 6);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Bagha', 7);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Bagmara', 7);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Charghat', 7);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Durgapur', 7);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Godagari', 7);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Mohanpur', 7);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Paba', 7);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Puthia', 7);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Tanore', 7);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Belkuchi', 8);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Chauhali', 8);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Kamarkhanda', 8);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Kazipur', 8);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Raiganj', 8);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Shahjadpur', 8);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Sirajganj Sadar', 8);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Tarash', 8);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Ullahpara', 8);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Biral', 9);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Birampur', 9);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Birganj', 9);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Bochaganj', 9);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Chirirbandar', 9);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Dinajpur Sadar', 9);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Ghoraghat', 9);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Hakimpur', 9);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Kaharole', 9);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Khansama', 9);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Nawabganj', 9);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Parbatipur', 9);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Phulbari', 9);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Gaibandha Sadar', 10);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Gobindaganj', 10);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Palashbari', 10);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Phulchhari', 10);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Sadullapur', 10);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Sughatta', 10);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Sundarganj', 10);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Bhurungamari', 11);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Char Rajibpur', 11);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Chilmari', 11);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Kurigram Sadar', 11);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Nageshwari', 11);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Phulbari', 11);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Rajarhat', 11);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Raomari', 11);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Ulipur', 11);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Aditmari', 12);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Hatibandha', 12);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Kaliganj', 12);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Lalmonirhat Sadar', 12);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Patgram', 12);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Dimla', 13);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Domar', 13);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Jaldhaka', 13);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Kishoreganj', 13);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Nilphamari Sadar', 13);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Saidpur', 13);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Atwari', 14);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Boda', 14);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Debiganj', 14);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Panchagarh Sadar', 14);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Tetulia', 14);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Badarganj', 15);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Gangachhara', 15);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Kaunia', 15);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Mithapukur', 15);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Pirgachha', 15);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Pirganj', 15);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Rangpur Sadar', 15);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Taraganj', 15);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Baliadangi', 16);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Haripur', 16);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Pirganj', 16);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Ranisankail', 16);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Thakurgaon Sadar', 16);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Ruhia', 16);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Bhully', 16);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Baksiganj', 17);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Dewanganj', 17);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Islampur', 17);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Jamalpur Sadar', 17);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Madarganj', 17);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Melandaha', 17);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Sarishabari', 17);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Bhaluka', 18);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Dhobaura', 18);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Fulbaria', 18);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Gafargaon', 18);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Gauripur', 18);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Haluaghat', 18);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Ishwarganj', 18);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Muktagachha', 18);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Mymensingh Sadar', 18);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Nandail', 18);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Phulpur', 18);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Tara Khanda', 18);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Trishal', 18);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Atpara', 19);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Barhatta', 19);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Durgapur', 19);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Kalmakanda', 19);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Khaliajuri', 19);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Kendua', 19);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Madan', 19);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Mohanganj', 19);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Netrokona Sadar', 19);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Purbadhala', 19);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Jhenaigati', 20);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Nakla', 20);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Nalitabari', 20);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Sherpur Sadar', 20);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Sreebardi', 20);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Amtali', 21);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Bamna', 21);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Barguna Sadar', 21);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Betagi', 21);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Patharghata', 21);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Taltali', 21);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Agailjhara', 22);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Babuganj', 22);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Bakerganj', 22);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Banaripara', 22);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Barisal Sadar', 22);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Gaurnadi', 22);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Hizla', 22);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Mehendiganj', 22);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Muladi', 22);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Wazirpur', 22);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Bhola Sadar', 23);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Burhanuddin', 23);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Char Fasson', 23);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Daulatkhan', 23);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Lalmohan', 23);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Manpura', 23);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Tazumuddin', 23);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Jhalokati Sadar', 24);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Kathalia', 24);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Nalchity', 24);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Rajapur', 24);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Bauphal', 25);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Dashmina', 25);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Dumki', 25);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Galachipa', 25);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Kalapara', 25);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Mirzaganj', 25);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Patuakhali Sadar', 25);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Rangabali', 25);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Bhandaria', 26);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Indurkani', 26);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Kawkhali', 26);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Mathbaria', 26);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Nazirpur', 26);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Nesarabad (Swarupkati)', 26);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Pirojpur Sadar', 26);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Ali Kadam', 27);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Bandarban Sadar', 27);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Lama', 27);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Naikhongchhari', 27);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Rowangchhari', 27);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Ruma', 27);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Thanchi', 27);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Akhaura', 28);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Bancharampur', 28);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Brahmanbaria Sadar', 28);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Kasba', 28);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Nabinagar', 28);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Nasirnagar', 28);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Sarail', 28);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Ashuganj', 28);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Bijoynagar', 28);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Chandpur Sadar', 29);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Faridganj', 29);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Haimchar', 29);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Haziganj', 29);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Kachua', 29);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Matlab Dakshin', 29);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Matlab Uttar', 29);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Shahrasti', 29);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Chandraganj', 29);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Anwara', 30);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Banshkhali', 30);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Boalkhali', 30);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Chandanaish', 30);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Fatikchhari', 30);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Hathazari', 30);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Karnaphuli', 30);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Lohagara', 30);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Mirsharai', 30);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Patiya', 30);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Rangunia', 30);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Raozan', 30);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Sandwip', 30);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Satkania', 30);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Sitakunda', 30);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Barura', 31);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Brahmanpara', 31);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Burichang', 31);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Chandina', 31);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Chauddagram', 31);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Daudkandi', 31);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Debidwar', 31);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Homna', 31);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Laksam', 31);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Lalmai', 31);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Muradnagar', 31);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Nangalkot', 31);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Cumilla Adarsha Sadar', 31);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Meghna', 31);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Titas', 31);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Monohargonj', 31);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Cumilla Sadar Dakshin', 31);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Chakaria', 32);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Cox''s Bazar Sadar', 32);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Kutubdia', 32);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Maheshkhali', 32);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Ramu', 32);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Teknaf', 32);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Ukhia', 32);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Pekua', 32);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Eidgaon', 32);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Matamuhuri', 32);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Chhagalnaiya', 33);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Daganbhuiyan', 33);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Feni Sadar', 33);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Parshuram', 33);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Sonagazi', 33);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Fulgazi', 33);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Dighinala', 34);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Khagrachhari Sadar', 34);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Lakshmichhari', 34);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Mahalchhari', 34);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Manikchhari', 34);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Matiranga', 34);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Panchhari', 34);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Ramgarh', 34);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Guimara', 34);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Lakshmipur Sadar', 35);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Raipur', 35);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Ramganj', 35);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Ramgati', 35);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Kamalnagar', 35);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Begumganj', 36);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Noakhali Sadar', 36);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Chatkhil', 36);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Companiganj', 36);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Hatiya', 36);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Senbagh', 36);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Sonaimuri', 36);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Subarnachar', 36);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Kabirhat', 36);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Bagaichhari', 37);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Barkal', 37);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Kawkhali (Betbunia)', 37);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Belaichhari', 37);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Kaptai', 37);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Juraichhari', 37);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Langadu', 37);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Naniyachar', 37);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Rajasthali', 37);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Rangamati Sadar', 37);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Dhamrai', 38);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Dohar', 38);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Keraniganj', 38);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Nawabganj', 38);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Savar', 38);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Alfadanga', 39);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Bhanga', 39);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Boalmari', 39);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Charbhadrasan', 39);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Faridpur Sadar', 39);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Madhukhali', 39);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Nagarkanda', 39);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Sadarpur', 39);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Saltha', 39);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Gazipur Sadar', 40);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Kaliakair', 40);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Kaliganj', 40);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Kapasia', 40);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Sreepur', 40);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Gopalganj Sadar', 41);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Kashiani', 41);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Kotalipara', 41);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Muksudpur', 41);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Tungipara', 41);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Austagram', 42);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Bajitpur', 42);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Bhairab', 42);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Hossainpur', 42);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Itna', 42);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Karimganj', 42);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Katiadi', 42);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Kishoreganj Sadar', 42);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Kuliarchar', 42);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Mithamain', 42);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Nikli', 42);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Pakundia', 42);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Tarail', 42);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Rajoir', 43);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Madaripur Sadar', 43);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Kalkini', 43);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Shibchar', 43);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Dasar', 43);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Daulatpur', 44);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Ghior', 44);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Harirampur', 44);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Manikgonj Sadar', 44);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Saturia', 44);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Shivalaya', 44);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Singair', 44);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Gazaria', 45);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Lohajang', 45);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Munshiganj Sadar', 45);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Sirajdikhan', 45);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Sreenagar', 45);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Tongibari', 45);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Araihazar', 46);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Bandar', 46);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Narayanganj Sadar', 46);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Rupganj', 46);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Sonargaon', 46);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Narsingdi Sadar', 47);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Belabo', 47);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Monohardi', 47);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Palash', 47);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Raipura', 47);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Shibpur', 47);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Baliakandi', 48);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Goalandaghat', 48);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Pangsha', 48);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Rajbari Sadar', 48);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Kalukhali', 48);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Bhedarganj', 49);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Damudya', 49);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Gosairhat', 49);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Naria', 49);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Shariatpur Sadar', 49);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Zajira', 49);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Gopalpur', 50);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Basail', 50);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Bhuapur', 50);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Delduar', 50);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Ghatail', 50);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Kalihati', 50);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Madhupur', 50);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Mirzapur', 50);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Nagarpur', 50);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Sakhipur', 50);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Dhanbari', 50);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Tangail Sadar', 50);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Bagerhat Sadar', 51);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Chitalmari', 51);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Fakirhat', 51);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Kachua', 51);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Mollahat', 51);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Mongla', 51);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Morrelganj', 51);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Rampal', 51);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Sarankhola', 51);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Alamdanga', 52);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Chuadanga Sadar', 52);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Damurhuda', 52);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Jibannagar', 52);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Abhaynagar', 53);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Bagherpara', 53);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Chaugachha', 53);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Jhikargachha', 53);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Keshabpur', 53);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Jashore Sadar', 53);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Manirampur', 53);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Sharsha', 53);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Harinakunda', 54);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Jhenaidah Sadar', 54);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Kaliganj', 54);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Kotchandpur', 54);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Maheshpur', 54);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Shailkupa', 54);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Batiaghata', 55);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Dacope', 55);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Dumuria', 55);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Dighalia', 55);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Koyra', 55);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Paikgachha', 55);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Phultala', 55);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Rupsha', 55);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Terokhada', 55);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Bheramara', 56);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Daulatpur', 56);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Khoksa', 56);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Kumarkhali', 56);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Kushtia Sadar', 56);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Mirpur', 56);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Magura Sadar', 57);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Mohammadpur', 57);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Shalikha', 57);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Sreepur', 57);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Gangni', 58);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Meherpur Sadar', 58);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Mujibnagar', 58);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Kalia', 59);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Lohagara', 59);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Narail Sadar', 59);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Assasuni', 60);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Debhata', 60);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Kalaroa', 60);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Kaliganj', 60);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Satkhira Sadar', 60);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Shyamnagar', 60);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Tala', 60);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Ajmiriganj', 61);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Bahubal', 61);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Baniyachong', 61);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Chunarughat', 61);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Habiganj Sadar', 61);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Lakhai', 61);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Madhabpur', 61);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Nabiganj', 61);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Shayestaganj', 61);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Barlekha', 62);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Juri', 62);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Kamalganj', 62);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Kulaura', 62);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Moulvibazar Sadar', 62);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Rajnagar', 62);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Sreemangal', 62);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Bishwamvarpur', 63);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Chhatak', 63);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Shantiganj', 63);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Derai', 63);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Dharamapasha', 63);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Dowarabazar', 63);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Jagannathpur', 63);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Jamalganj', 63);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Sullah', 63);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Sunamganj Sadar', 63);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Tahirpur', 63);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Madhyanagar', 63);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Balaganj', 64);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Beanibazar', 64);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Bishwanath', 64);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Companiganj', 64);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Dakshin Surma', 64);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Fenchuganj', 64);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Golapganj', 64);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Gowainghat', 64);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Jaintiapur', 64);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Kanaighat', 64);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Osmani Nagar', 64);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Sylhet Sadar', 64);
INSERT INTO Thanas (Name, DistrictId) VALUES (N'Zakiganj', 64);